spring:
  data:
    mongodb:
      host: localHost
      port: 0
      database: taskTrackingDb

de:
  flapdoodle:
    mongodb:
      embedded:
        version: 4.0.2

mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.task.management.mongodb.changelogs
  mongo-db:
    write-concern:
      journal: false
    read-concern: local

server:
  port: 8080