server:
  port: 8080

spring:
  data:
    mongodb:
      host: localHost
      port: 27017
      database: taskTrackingDb
      auto-index-creation: true

#  main:
#    allow-circular-references: true

#de:
#  flapdoodle:
#    mongodb:
#      embedded:
#        version: 4.0.2

mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.task.management.mongodb.changelogs
  mongo-db:
    write-concern:
      journal: false
    read-concern: local

JwtToken:
  expirationDays: 7
  secret: SuperSecret
