version: '3.8'
services:

  mongo:
    image: mongo:7.0
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=taskTrackingDb

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_BASICAUTH: false

  discovery-server:
    build:
      context: ./discovery-server
    container_name: discovery-server

  config-server:
    build:
      context: ./config-server
    container_name: config-server