server:
  port: 8081

eureka:
  client:
    fetch-registry: true

spring:
  data:
    mongodb:
      host: localHost
      port: 27017
      database: taskTrackingDb
      auto-index-creation: true

mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.task.management.mongodb.changelogs
  mongo-db:
    write-concern:
      journal: false
    read-concern: local