server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/DmitryShadrin1989/task-management-config-repo

management:
  endpoints:
    web:
      exposure:
        include: "*"